menus/urls.py
from django.conf.urls import url
from .views import (
    ItemListView,
    ItemDetailView,
    ItemCreateView,
    ItemUpdateView,
)
urlpatterns = [

    url(r'^create/$', ItemCreateView.as_view(), name='create'),
    # url(r'^(?P<pk>\d+)/edit/$', ItemUpdateView.as_view(), name='update'),
    url(r'^(?P<pk>\d+)/$', ItemUpdateView.as_view(), name='detail'),
    url(r'^$', ItemListView.as_view(), name='list'),
  
]

muypicky/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from  django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import TemplateView
from profiles.views import ProfileFollowToggle, RegistrationView, activate_user_view
from menus.views import HomeView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^registration/$', RegistrationView.as_view(), name='registration'),
    url(r'^activate/(?P<code>[a-z0-9].*)/$', activate_user_view, name='activate'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^profile-follow/$', ProfileFollowToggle.as_view(), name='follow'),
    url(r'^restaurants/', include('restaurants.urls', namespace='restaurants')),
    url(r'^items/', include('menus.urls', namespace='menus')),
    url(r'^profiles/', include('profiles.urls', namespace='profiles')),
    url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^contact/$', TemplateView.as_view(template_name='contact.html'), name='contact'),
]

restaurants/urls.py
from django.conf.urls import url
from .views import (
    RestaurantListView,
    RestaurantDetailView,
    RestaurantCreateView,
    RestaurantUpdateView,
)
urlpatterns = [
    url(r'^$', RestaurantListView.as_view(), name='list'),
    url(r'^create/$', RestaurantCreateView.as_view(), name='create'),
    # url(r'^(?P<slug>[\w-]+)/edit/$', RestaurantUpdateView.as_view(), name='edit'),
    url(r'^(?P<slug>[\w-]+)/$', RestaurantUpdateView.as_view(), name='detail'),
    # url(r'^restaurant/(?P<pk>\d+)/$', RestaurantDetailView.as_view()),
]

restaurants/models.py
from django.db import models
from django.db.models import Q
from django.db.models.signals import pre_save, post_save
from django.core.urlresolvers import reverse

from .utils import unique_slug_generator
from .validators import validate_category
from django.conf import settings
# Create your models here.

User = settings.AUTH_USER_MODEL

class RestaurantLocationQuerySet(models.QuerySet):
	def search(self, query):	#RestaurantLocation.objects.all().search(query) #RestaurantLocation.objects.filter(something).search()
		if query:
			query = query.strip()
			return self.filter(
				Q(name__icontains=query) |
				Q(location__icontains=query) |
				Q(category__icontains=query) |
				Q(item__name__icontains=query) |
				Q(item__contents__icontains=query)
				).distinct()
		else:
			return self

class RestaurantLocationManager(models.Manager):
	def get_queryset(self):
		return RestaurantLocationQuerySet(self.model, using=self._db)
	def search(self, query):	#restaurantLocation.objects.search()
		return self.get_queryset().search(query)

class RestaurantLocation(models.Model):
	owner		= models.ForeignKey(User) # Django Models Unleached JOINCFE.com
	name		= models.CharField(max_length=120)
	location	= models.CharField(max_length=120, null=True, blank=True)
	category	= models.CharField(max_length=120, null=True, blank=True, validators=[validate_category])
	timestamp	= models.DateTimeField(auto_now_add=True)
	updated		= models.DateTimeField(auto_now=True)
	#my_date_field = models.DateTimeField(auto_now=False, auto_now_add=False)
	slug		= models.SlugField(null=True, blank=True)

	objects = RestaurantLocationManager()		# add Model.objects.all()

	class Meta:
		ordering = ['-updated', '-timestamp']
	
	def __str__(self):
		return self.name

	def get_absolute_url(self):		#get_absolute_url
		# return f"/restaurant/{self.slug}"
		# return reverse('restaurant')
		return reverse('restaurants:detail', kwargs={'slug': self.slug})


	@property
	def title(self):
		return self.name

def rl_pre_save_receiver(sender, instance, *args, **kwargs):
	# print('saving...')
	# print(instance.timestamp)
	instance.category = instance.category.capitalize()

	if not instance.slug:
		instance.slug = unique_slug_generator(instance)


# def rl_post_save_receiver(sender, instance, created, *args, **kwargs):
# 	print('saved...')
# 	print(instance.timestamp)
# 	if not instance.slug:
# 		instance.slug = unique_slug_generator(instance)
# 		instance.save()


pre_save.connect(rl_pre_save_receiver, sender=RestaurantLocation)
# post_save.connect(rl_post_save_receiver, sender=RestaurantLocation)

TITLE_CHOICES = (
		('MR', 'Mr.'),
		('MRS', 'Mrs.'),
		('MS', 'Ms.'),
		# ('MM', 'Mm.'),
	)

class Author(models.Model):
	name = models.CharField(max_length=100)
	title = models.CharField(max_length=3, choices=TITLE_CHOICES)
	birth_date = models.DateTimeField(blank=True, null=True)

	def __str__(self):
		return self.name

class Book(models.Model):
	authors = models.ManyToManyField(Author)
	name = models.CharField(max_length=100)

restaurants/forms.py
from django import forms
from restaurants.models import RestaurantLocation, Author, Book
from .validators import validate_category

class RestaurantCreateForm(forms.Form):
	name		= forms.CharField(label="Rest Name")
	location	= forms.CharField(required=False)
	category	= forms.CharField(required=False)

	def clean_name(self):
		name = self.cleaned_data.get('name')
		if name == 'Hello':
			raise forms.ValidationError(
				('Invalid value: %(value)s'),
    				params={'value': name},
				)
		return name

class RestaurantLocationCreateForm(forms.ModelForm):
	# email		= forms.EmailField()
	# category = forms.CharField(required=False, validators=[validate_category])
	class Meta:
		model = RestaurantLocation
		fields = [
			'name',
			'location',
			'category',
		]

	def clean_name(self):
		name = self.cleaned_data.get('name')
		if name == 'create':
			raise forms.ValidationError('Invalid value: %(value)s',
    				params={'value': name},
				)
		return name

	# def clean_email(self):
	# 	email = self.cleaned_data.get('email')
	# 	if ".edu" in email:
	# 		raise forms.ValidationError('We do not accept : %(value)s',
 #    				params={'value': '.edu'},
	# 			)
	# 	return email

restaurants/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView
from restaurants.models import	RestaurantLocation
from menus.models import Item
from restaurants.forms import RestaurantCreateForm, RestaurantLocationCreateForm


class RestaurantListView(LoginRequiredMixin,ListView):
		def get_queryset(self):
			return RestaurantLocation.objects.filter(owner = self.request.user).order_by('-updated')

class RestaurantDetailView(LoginRequiredMixin, DetailView):
	def get_queryset(self):
			return RestaurantLocation.objects.filter(owner = self.request.user)


class RestaurantCreateView(LoginRequiredMixin, CreateView):
	template_name = 'form.html'
	form_class = RestaurantLocationCreateForm
	model = RestaurantLocation

	def form_valid(self, form):
		instance = form.save(commit=False)
		instance.owner = self.request.user
		return super().form_valid(form)	# super(RestaurantCreateView,self).form_valid(form)
	
		
	def get_context_data(self, *args, **kwargs):
		context = super().get_context_data(*args, **kwargs)
		context['title'] = 'Add Restaurant'
		return context

class RestaurantUpdateView(LoginRequiredMixin, UpdateView):
	template_name = 'restaurants/detail_update.html'
	form_class = RestaurantLocationCreateForm
	model = RestaurantLocation
		
	def get_context_data(self, *args, **kwargs):
		context = super().get_context_data(*args, **kwargs)
		# menu_items = Item.objects.filter(restaurant=self.kwargs.get('restaurantlocation'))
		context['title'] = 'Update Restaurant'
		# context['menu_items'] = menu_items
		# print(context)
		return context

restaurants/templates/restaurants/detail_update.html
{% extends 'base.html' %}
{% block head_title %} {{ title }} | {{ block.super }}{% endblock %}
{% block content %}
<h1>Detail {{ title }}</h1>
<h2>Name: {{ form.instance.name }}</h2>  
<p>Location: {{ form.instance.location }}</p>
<p>Category: {{form.instance.category}}</p>
<i><small>Created by <strong>{{ form.instance.owner }}</strong> on {{ form.instance.timestamp}} updated {{form.instance.updated|timesince}} ago</small></i>

<hr/>
<h3>Make Changes</h3>

{% include 'snippets/form_snippet.html' with form=form %}

<hr/>
{% if menu_items %}
{% for item in menu_items %}
	<ul>
		<li>item</li>
	</ul>
{% endfor %}
{% endif %}
{% endblock %}

restaurants/templates/restaurants/restaurant_create.html
{% extends 'base.html' %}
{% block head_title %}{{ title }} | {{ block.super }}{% endblock %}
{% block content %}
	<h2>{{ title }}</h2>
	<form method="POST"> {% csrf_token %}
		{% if form.errors %}
			{{ form.errors }}
		{% endif %}
		{{ form.as_p }}
		<input type="submit" name="submit" value="Sumbit">
	</form>
	
{% endblock %}

restaurants/templates/restaurants/restaurantlocation_detail.html
{% extends 'base.html' %}
{% block head_title %}{{ title }} | {{ block.super }}{% endblock %}
{% block content %}
	<h1>Detail Restaurant</h1>
	<h2>Name: {{ object.name }}</h2>  <small>Category: {{object.category}} </small>
	<p>Location: {{ object.location }}</p>
	<i>Created by <strong>{{ object.owner }}</strong> on {{ object.timestamp}}, updated {{object.updated|timesince}} ago</i>

{% endblock %}

restaurants/templates/restaurants/restaurantlocation_list.html
{% extends 'base.html' %}
{% block head_title %}Restaurant | {{ block.super }}{% endblock %}
{% block content %}
	<h2>My Restaurant <a href="{% url 'restaurants:create' %}"> <small>Add </small></a></h2> 
	<ul>
	{% for obj in object_list %}
		<li><a href="{{ obj.get_absolute_url }} ">{{obj.name }}</a></li>
	{% empty %}
		<li><a href="{% url 'restaurants:create' %}"> <small>Add New One</small></a></li>
	{% endfor %}
	</ul>
{% endblock %}