menus/urls.py
from django.conf.urls import url
from .views import (
    ItemListView,
    ItemDetailView,
    ItemCreateView,
    ItemUpdateView,
)
urlpatterns = [

    url(r'^create/$', ItemCreateView.as_view(), name='create'),
    # url(r'^(?P<pk>\d+)/edit/$', ItemUpdateView.as_view(), name='update'),
    url(r'^(?P<pk>\d+)/$', ItemUpdateView.as_view(), name='detail'),
    url(r'^$', ItemListView.as_view(), name='list'),
  
]

muypicky/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from  django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import TemplateView
from profiles.views import ProfileFollowToggle, RegistrationView, activate_user_view
from menus.views import HomeView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^registration/$', RegistrationView.as_view(), name='registration'),
    url(r'^activate/(?P<code>[a-z0-9].*)/$', activate_user_view, name='activate'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^profile-follow/$', ProfileFollowToggle.as_view(), name='follow'),
    url(r'^restaurants/', include('restaurants.urls', namespace='restaurants')),
    url(r'^items/', include('menus.urls', namespace='menus')),
    url(r'^profiles/', include('profiles.urls', namespace='profiles')),
    url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^contact/$', TemplateView.as_view(template_name='contact.html'), name='contact'),
]

menus/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.conf import settings
from restaurants.models import RestaurantLocation

class Item(models.Model):
	# associations
	user		= models.ForeignKey(settings.AUTH_USER_MODEL)
	restaurant 	= models.ForeignKey(RestaurantLocation)
	# item stuff
	name		= models.CharField(max_length=120)
	contents	= models.TextField(help_text='Seperate each item by comma')
	excludes	= models.TextField(blank=True, null=True, help_text='Seperate each item by comma')
	public		= models.BooleanField(default=True)
	timestamp	= models.DateTimeField(auto_now_add=True)
	updated		= models.DateTimeField(auto_now=True)

	
	class Meta:
		ordering = ['-updated', '-timestamp']

	def __str__(self):
		return self.name
		
	def get_contents(self):
		return self.contents.split(',')

	def get_excludes(self):
		return self.excludes.split(',')

	def get_absolute_url(self):		#get_absolute_url
		return reverse('menus:detail', kwargs={'pk': self.pk})

menus/forms.py
from django import forms

from .models import Item
from restaurants.models import RestaurantLocation

class ItemForm(forms.ModelForm):
	class Meta:
		model = Item
		fields = [
			'restaurant',
			'name',
			'contents',
			'excludes',
			'public',
		]

	def __init__(self, user=None, *args, **kwargs):
		# print(kwargs.pop('user'))
		# print(user)
		print(kwargs)
		super().__init__(*args, **kwargs)
		self.fields['restaurant'].queryset = RestaurantLocation.objects.filter(owner=user)#.exclude(item__isnull=False)

menus/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.views.generic import View, ListView, DetailView, CreateView, UpdateView

from .forms import ItemForm
from .models import Item

class HomeView(View):
	def get(self, request, *args, **kwargs):
		if not request.user.is_authenticated():
			return render(request, 'home.html',{})

		user = request.user
		is_following_user_ids = [x.user.id for x in user.is_following.all()]
		qs = Item.objects.filter(user__id__in=is_following_user_ids, public=True).order_by('-updated')

		return render(request, 'menus/home-feed.html', {'object_list': qs})

class ItemListView(ListView):
	def get_queryset(self):
		return Item.objects.filter(user=self.request.user)

class ItemDetailView(DetailView):
	def get_queryset(self):
		return Item.objects.filter(user=self.request.user)

class ItemCreateView(LoginRequiredMixin, CreateView):
	template_name = 'form.html'
	form_class = ItemForm
	model = Item
	
	def form_valid(self, form):
		instance = form.save(commit=False)
		instance.user = self.request.user
		return super().form_valid(form)	# super(RestaurantCreateView,self).form_valid(form)

	def get_form_kwargs(self):
		kwargs = super().get_form_kwargs()
		kwargs['user'] = self.request.user
		# kwargs['instance'] = Item.objects.filter(user=self.request.user).first()
		return kwargs

	# def get_queryset(self):
	# 	model = Item
	# 	return super().get_queryset()
	# 	return Item.objects.filter(user=self.request.user)

	def get_context_data(self, *args, **kwargs):
		context = super().get_context_data(*args, **kwargs)
		context['title'] = 'Add Item'
		return context

class ItemUpdateView(LoginRequiredMixin, UpdateView):
	template_name = 'menus/detail_update.html'
	form_class = ItemForm
	model = Item
	# def get_queryset(self):
	# 	return super().get_queryset()
		# return Item.objects.filter(user=self.request.user)

	def get_context_data(self, *args, **kwargs):
		context = super().get_context_data(*args, **kwargs)
		context['title'] = 'Update Item'
		return context

	def get_form_kwargs(self):
		kwargs = super().get_form_kwargs()
		kwargs['user'] = self.request.user
		return kwargs

menus/templates/menus/detail_update.html
{% extends 'base.html' %}
{% block head_title %} {{ title }} | {{ block.super }}{% endblock %}
{% block content %}

<h1>{{ form.instance.name }}</h1>
<p>Location: {{ form.instance.restaurant.name }}</p>
<h2>Menu Items</h2>
{% if form.instance.contents %}
Contents
<ul>
	{% for item in form.instance.get_contents %}
	<li>{{ item }}</li>
	{% endfor %}
</ul>
{% endif %}
{% if form.instance.excludes %}				
Excludes
<ul>
	{% for item in form.instance.get_excludes %}
	<li>{{ item }}</li>
	{% endfor %}
</ul>
{% endif %}

<hr/>

<h3>Make Changes</h3>

{% include 'snippets/form_snippet.html' with form=form %}

{% endblock %}

menus/templates/menus/home-feed.html
{% extends 'base.html' %}
{% block head_title %}Menu Items | {{ block.super }}{% endblock %}
{% block content %}
	<div class="row">
	<div class="col-sm-9 text-center col-sm-offset-3">
		<h1>User Following Feed</h1>
		{% for obj in object_list %}
		<div class="thumbnail">
		<h3><a href="{% url 'profiles:detail' username=obj.user.username %}">{{ obj.user.username }}</a></h3>
		<h4>{{ obj.name }}</h4>
		<p><a href="{% url 'profiles:detail' username=obj.user.username %}?q={{obj.restaurant.title}}">{{obj.restaurant.title}}</a> | <a href="{% url 'profiles:detail' username=obj.user.username %}?q={{obj.restaurant.location}}">{{obj.restaurant.location}}</a> | <a href="{% url 'profiles:detail' username=obj.user.username %}?q={{obj.restaurant.category}}">{{obj.restaurant.category}}</a></p>
		<p>
		<b>{{ obj.name }}:</b> with
			{% for ing in obj.get_contents %}
				<a href="{% url 'profiles:detail' username=obj.user.username %}?q={{ing}}"> {{ ing }}</a>
			{% endfor %}
		</p>
		</div>
		{% endfor %}
	</div>
	</div>

{% endblock %}

menus/templates/menus/item_detail.html
{% extends 'base.html' %}
{% block head_title %}Menu Items | {{ block.super }}{% endblock %}
{% block content %}
<h1>{{ object.name }}</h1>
<p>Location: {{ object.restaurant.name }}</p>
<h2>Menu Items</h2>
{% if object.contents %}
Contents
<ul>
	{% for item in object.get_contents %}
	<li>{{ item }}</li>
	{% endfor %}
</ul>
{% endif %}
{% if object.excludes %}				
Excludes
<ul>
	{% for item in object.get_excludes %}
	<li>{{ item }}</li>
	{% endfor %}
</ul>
{% endif %}
{% endblock %}

menus/templates/menus/item_list.html
{% extends 'base.html' %}
{% block head_title %}Menu Items | {{ block.super }}{% endblock %}
{% block content %}
	<h2>Menu Items <small><a href="{% url 'menus:create' %}"> Add</a></small></h2>
	<ul>
	{% for obj in object_list %}
		<li><a href="{{ obj.get_absolute_url }}">{{obj.name }}</a><br/>
			{% if obj.contents %}
			Contents
			<ul>
				{% for item in obj.get_contents %}
				<li>{{ item }}</li>
				{% endfor %}
			</ul>
			{% endif %}
			{% if obj.excludes %}				
			Excludes
			<ul>
				{% for item in obj.get_excludes %}
				<li>{{ item }}</li>
				{% endfor %}
			</ul>
			{% endif %}
		</li>
	{% empty %}
		<li><a href="{% url 'menus:create' %}"> Add Menu Item</a></li>
	{% endfor %}
	</ul>
{% endblock %}